version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www
        depends_on:
            - mysql

    mysql:
        image: mysql:8.3.0
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel
        volumes:
            - mysql-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
        depends_on:
            - mysql

volumes:
    mysql-data:
